name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: material-components-web-miso
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        name: Build sample app
        id: build
      - run: |
          cd sample-app-jsaddle
          nix-build -A release
          mkdir deploy
          cp result/bin/app.jsexe/lib.js deploy/lib.js
          cp result/bin/app.jsexe/out.js deploy/out.js
          cp result/bin/app.jsexe/rts.js deploy/rts.js
          cp result/bin/app.jsexe/runmain.js deploy/runmain.js
          
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'sample-app-jsaddle/deploy'
          destination_dir: ''
